### ISSUE TITLE
implicit redis dependence causes issues with webpack builds

### ISSUE THREAD

**Issue by starpit** [apache/openwhisk-composer#63]
webpack scans source code for imports, and treats any it thusly discovers as serious statements of dependence. openwhisk-composer has a require('redis'), but no matching dependence resolution in its package.json. as a result, webpack gets a bit confused.

one can place redis (and redis-commands) in the `externals` section of one's webpack configuration. but... one must do this in a blanket fashion. what if module A of my application has this implicit redis dependence, and module B has an actual (and important) dependence on redis? i cannot therefore take a blanket "externals" treatment of redis, but this is the only option i see, to patch over openwhisk-composer's unstated redis dependence.

**Comment by tardieu** [comment]
I am not sure I understand the issue. Redis does not appears in `package.json` dependencies because composer does not require redis. The execution of the conductor action code generated by composer may require redis, but does not require composer... The redis dependency must be satisfied by the openwhisk runtime image, not the composer install.

Are you saying that webpack detects the require statement, which causes a problem for kui?

I can obfuscate the `require('redis')` bit if you tell me how to fool webpack.

**Comment by starpit** [comment]
webpack sees an import of `composer/client`, which in turn imports `./conductor`, which in turn imports (possibly) `redis`, which leads to a webpack build error.

option 1) isolate the conductor and client code, so that use of the client does not chain-import conductor.js

option 2) if hacks are necessary, i think you can defeat the webpack dependence crawl by doing a string-import, something like
```javascript
const redis = 'redis'
require(redis)
```

**Comment by starpit** [comment]
oh, i think you can also add webpack magic comments:

```javascript
require('/* webpackIgnore: true */ redis')
```
